on:
  push:
  pull_request:
  schedule:
    - cron: '13 11 * * *'
jobs:
  pythonbuild:
    runs-on: ubuntu-22.04
    steps:
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libssl-dev pkg-config

      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-pythonbuild-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: |
          cargo build --release

      - name: Upload pythonbuild Executable
        uses: actions/upload-artifact@v3
        with:
          name: pythonbuild
          path: target/release/pythonbuild

  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          # Cross-compiles can't do PGO.
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'noopt'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'lto'

          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'aarch64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # Cross-compiles can't do PGO and require Python 3.9.
          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'armv7-unknown-linux-gnueabi'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # Cross-compiles can't do PGO and require Python 3.9.
          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'armv7-unknown-linux-gnueabihf'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # We don't publish noopt builds when PGO is available.
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'lto'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'pgo'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'pgo+lto'

          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo+lto'

          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo'
          - target_triple: 'i686-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo+lto'

          # Cross-compiles can't do PGO and require Python 3.9.
          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'mips-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # Cross-compiles can't do PGO and require Python 3.9.
          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'mipsel-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # Cross-compiles can't do PGO and require Python 3.9.
          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 's390x-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # We don't publish noopt builds when PGO is available.
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'lto'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'pgo'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.8'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo'
          - target_triple: 'x86_64-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo'
          - target_triple: 'x86_64_v2-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo'
          - target_triple: 'x86_64_v3-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'pgo+lto'

          # GitHub Actions runners don't support x86-64-v4 so we can't PGO.
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.9'
            optimizations: 'lto'

          # GitHub Actions runners don't support x86-64-v4 so we can't PGO.
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v4-unknown-linux-gnu'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # musl doesn't support PGO.
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.8'
            optimizations: 'noopt'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.8'
            optimizations: 'lto'

          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'x86_64-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'lto'

          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v2-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'lto'

          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v3-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'lto'

          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'x86_64_v4-unknown-linux-musl'
            py: 'cpython-3.10'
            optimizations: 'lto'

    needs:
      - pythonbuild
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download pythonbuild
        uses: actions/download-artifact@v3
        with:
          name: pythonbuild
          path: build

      - name: Build
        run: |
          ./build-linux.py --target-triple ${{ matrix.build.target_triple }} --python ${{ matrix.build.py }} --optimizations ${{ matrix.build.optimizations }}

      - name: Validate Distribution
        run: |
          chmod +x build/pythonbuild
          build/pythonbuild validate-distribution dist/*.tar.zst

      - name: Upload Distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build.py }}-${{ matrix.build.target_triple }}
          path: dist/*
